### PR TITLE
Added all data to the database.

### PR DESCRIPTION
**Pull request by radi-cho**
Added all needed items to the database (`./server/database/index.js`)

### CODE REVIEW

**Comment by radi-cho** [comment]
Okay. No problems - I'll fix fix these things (not conflicts - the images and whatever).

**Comment by retrixe** [comment]
It's not a problem ._.
It was simply our schema didn't provide enough information to meet our needs, nothing I could do about it, I had to add internalLink and divSpacing.

And the image thing was already there.

Could you test the query in projectDataRetriever.js in /graphiql and check if it works with your database, and if the data it delivers is the same as your database (it should be inside an object allCards inside data in graphiql)?

**Comment by radi-cho** [comment]
I didn't test it, because i hadn't time. I filled data and pushed it... that's why i told `no problem`, because I know the problem is in me. I didn't tested... but actually sent you review request - habit...

**Comment by radi-cho** [comment]
"`divSpacing is the height of the first div in CardMedia`" or CardContent, @retrixe?

**Comment by retrixe** [comment]
Uh, I'll review this once the schema is stable because I'm still working on this.

**Comment by radi-cho** [comment]
Cool

**Pull request merged**
