### PR TITLE
RSG-Chess-mobile image again added to the card.

### PR DESCRIPTION
**Pull request by radi-cho**
The new image of rsg-chess-mobile (#8) added again to the card

### CODE REVIEW

**Comment by radi-cho** [comment]
I know this card soon will be replaced with Apollo and GraphQL (#5) but....

**Comment by retrixe** [comment]
No. Not right now.

**Comment by radi-cho** [comment]
`Not right now` means `maybe later` or what, @retrixe ?

**Comment by retrixe** [comment]
When adults say not right now, it probably means no.

**Comment by radi-cho** [comment]
"adults"?

**Comment by retrixe** [comment]
lol forget it

**Comment by radi-cho** [comment]
Go to slack

**Pull request closed without merging**
