### PR TITLE
Link added to the image in the toolbar

### PR DESCRIPTION
**Pull request by radi-cho**
#### When click the icon in the left side of the toolbar redirecting to the home page.

Every big website has icon in the left top corner that redirects you to the homepage - YouTube, Google, bing, ect. I think this is good idea. Just added small `a` tag. Waiting for your opinion....

### CODE REVIEW

**Comment by retrixe** [comment]
**Some perspective on what you're used to and what you should do:** Using Next.js or Meteor is significantly different from create-react-app. OOTB it doesn't use modern technologies like SSR (used in Next.js, supported in Meteor), server programming (used in Meteor/possible with Next.js) and SPAs (Next.js/Meteor use it OOTB, possible in create-react-app with lots of pain) and it isn't preferable. I will tell you, you need to learn a lot to learn true React. CRA is utter crap. Try learning Next.js, it is really easy, opinionated, configurable, supports Express/Koa/Hapi/Micro for server-side code and uses SSR and SPA tech with zero configuration. It's not true zero configuration, because you will need to configure Flow/TypeScript/CoffeeScript or whatever yourself, configure Babel yourself and linters like ESLint. But you get so much efficiency and power with it, it's crazy. Major companies use Next.js, but none use CRA. It's a must you should learn if you're used to scaffolding tools like CRA. Get rid of them. Also, there is `create-next-app`, which allows you to fetch an example from Next.js' repo (they have over a 100) so Flow/TS/CS/Babel are pre-configured and ESLint can be configured in seconds. The fact that you control your code style is very significant. Also, CRA has HTML. Next.js teaches you to think React, and kills HTML. That's how frameworks should work. CRA is bad for even tiny projects. Next.js is not overkill for even a webpage with one page if it makes sense to have JavaScript.
The only good scaffolding tool is CRNA (create-react-native-app). Everything else is bad.

**Now, to the PR.**
Well, uh, the way it works is wrong. This is an SPA with Next.js and not CRA (which can also generate SPAs, but it's a pain). So you would need `Link`.

Also, it seems unorthodox that this is done from the icon. When it comes to Google and Bing and YouTube and Microsoft, they have a logo with their name on it. We don't. They are also massive brands and you can figure their logo even if it isn't written. Not one person knows RSG-Group. They only know it's a couple of people who make projects. I actually did have a concept for a back button in Chess but it never shipped. There's also an empty intersection page as well.

Right now, I have too much on my plate like threadripper, Area51, blog, decaffeinater, electron-installer-linux, wallpapers, the upcoming vsc-sync-settings and some other projects. Let me sort my life out, then we can return to UX, navigation and Material Design. I'll close this, no offense, but right now, there's no way this PR will do anything, and it is non-functional because this is an SPA. I will consider this PR in the future, and I plan to go back to the drawing board with `website` sometime after my examinations which end on 13th October. They're starting 26th September.

I simply don't have time. Or resources. In the future when I have both, I will return to UX and design with `website` and take this PR into considerations. Till then, I will regretfully say it won't make the cut. Feel free to make any suggestions. Till then, adios.

**Comment by radi-cho** [comment]
Ok, first part is good, but it isn't for here.

Also you're using `a` tag too:
```
<a href='https://github.com/RSG-Group' title='Our GitHub Page' target='_blank' rel='noopener noreferrer'>
    <IconButton color='contrast' aria-label='Our GitHub Page'><GitHubLogo /></IconButton>
</a>
```

Third: when I opened issues you fixed them for minutes, but when opened feature request you closed it, because you haven't time... I understand you for the time, but... how you fixed issues even when you haven't time - now please not say my attitude is bad.
And logo with name or no, whatever. Big brand or no, whatever - we need to become "`big brand`" to be able to create our logo and add Link to it?

My idea was just one link - with `Link`, `a`, CRA, SPA or whatever - just link... You started speaking about code style, Next.js, Big Brand. I want our websites to look like like we're big brand...

### Redirection in the logo is helpful. I know nobody (omit me) won't click this logo (For now), but one link isn't very work. Again - with `a`, `Link` or whatever, my idea was link (no `Link` tag, I want to say "[link](https://en.wikipedia.org/wiki/Hyperlink)") my idea wasn't `a` tag.

I will open one more PR with another changes soon. Actually I also contribute to RSG-Group and i have permissions to add stuff to our website. I'm open for your opinion, of course but after suggesting them, not now...

**Comment by retrixe** [comment]
1. `a` tag is for external linking. Linking within the website must be done with `Link` for transitioning state, efficient code splitting and preventing redirects which reload resources.

2. Your issues were subtle but important. I have time to fix tiny bugs. I don't have time to start reworking the webpage and stuff. We can talk about UX and UI later, but not now. I have examinations, do you understand? If I fail, or get okayish marks, I am not going to be able to accomplish anything because the world works like that. I don't have time for redesigning UIs right now when my life's future is in question.

As for big brand, I am saying that we don't need to become a big brand, I am simply saying that no one will be clicking on the logo because it doesn't really seem to be much benefit. People won't know the logo is ours or not. For your sake, I'll reopen this and add this functionality because you seem to care about this a lot. The real purpose of the logo was to add space between the drawer button and the text because the IconButton ripple was interfering with the text. Lol.

Also, I began talking about this because I would prefer you to know UX, design and React if you're working on this repository, because this repository is heavy on next-gen features and advanced UX. CRA means create-react-app. SPAs mean single page applications which only have one HTML file and do everything, navigation, webpages, etc in React. This website is an SPA and you need to learn stuff like `react-router` for work on web applications like this. And UX and design are highly important in practical programming, be it Vue, Polymer, Angular, React, hell jQuery or Backbone, thinking what the user will manipulate is highly important.

Anyways, fine, I'll add this.

**Comment by radi-cho** [comment]
1. You're right. `Link` is for SPA, `a` for "`outside SPA`", LOL 😆 
2. Yes, I understood. Sorry, I won't make it difficult for you to learn for the examinations... 😞 

The last part.... I know what is CRA and SPA - just used "`with Link, a, CRA, SPA or whatever`" because this was sarcasm. Also I can work with `react-router` very well. I'm good at SPA. Do you remember classroom. It was SPA, but I left this project, because our projects was (and now they're) better more interesting and awesome...
Also do you remember RSG-Mail. It was MESS if you see code you won't be able to understand nothing, just nothing... Because i wrote it when i was 8... Before few weeks I started rewriting it into SPA. But maybe I will left this project, too...

It's cool you reopened this. I'm busy too but will push changes (`Link` instead `a`). 🏷

**Comment by retrixe** [comment]
Well, that's all :100: but if you would learn Next.js and Meteor, you will find yourself using best practices and your life will become easy as butter.

**Comment by radi-cho** [comment]
Cool

**Comment by retrixe** [comment]
@radi-cho also, note, Link is not for SPAs. It's a Next.js specific component. :unamused:

**Comment by radi-cho** [comment]
react-router, too. @retrixe 
Hey, yes, it isn't for SPAs, it's specific react-router, next.js, ect. component (used for SPA with them...)

**Comment by radi-cho** [comment]
Also it isn't deployed... No worries. Deploy it when you have time. It isn't important @retrixe

**Comment by retrixe** [comment]
Deploys will be made every month and I'll be adding a marker to each release in the drawer which website version it is.

**Comment by radi-cho** [comment]
Okay.
But when we have breaking changes (bug or important new card, for example) we won't wait a month to deploy, right?

**Comment by retrixe** [comment]
Technically, we will. If there is a bug, then it will be September 2017 Patch 1 Release. New cards will have to wait. UX changes will have to wait as well.

**Comment by radi-cho** [comment]
okay, cool

**Pull request closed without merging**
