### PR TITLE
October 2017 Release

### PR DESCRIPTION
**Pull request by radi-cho**
## All things that we have to add up to `October 2017 Release`
Some of the things from #12 will be completed with this PR, others have to be added up to November release

### 1. Make cards the same size on all platforms.
so... I added few styles to the cards and the result is:
image
image
_View the first commit_
### 3. Internationalization makes life good
OK, so you (maybe) can translate the website to Hindi and I to Bulgarian, for other languages we're going to use Google translate or whatever in the internet. _This also maybe have to wait November 2017 if we haven't time (...we haven't)_.
### 4. Performance and optimization is needed.
**Yeah...** _but with every new commit we're improving the performance and optimization_

### I think that's all for this PR now... I'm going to comment the #12 about switching to TypeScript and Koa and adding blog.

### CODE REVIEW

**Comment by retrixe** [comment]
1. I actually did this. What I want to do is make the image size a multiple of 8 to comply with Material Design, and shift the buttons to the bottom, for which I have found a solution (hint: flexbox). What I need.. is a weekend. Tomorrow I can sneak my computer and in the 2 hours I get, I can work on this. So kill commit 0980fac. I don't know if verticalAlign will work, I'm a bit sceptic after Sass told me it doesn't exist. Also, I need to make images multiples of 8 in their height as well.

2. Yes, remove buttonSpacing, I will do. But show me a screenshot of `{ cursor: pointer }`.

3. Internationalisation can wait till November, agreed..

4. Performance can be tweaked. Performance must be tweaked.

Indeed, I will have to make these changes myself on another branch. So, I will close this, but I will add some of these changes to `website`. But what about `blog`?

**Comment by radi-cho** [comment]
Hear... You just killed this PR.
`I will have to make these changes myself on another branch.` - why yourself? whatever just close this PR.

**Comment by radi-cho** [comment]
`What about blog?`
@retrixe - if you want divide tasks or whatever. I'm very happy about the blog...

**Comment by retrixe** [comment]
Myself because many changes you did were unnecessary (excluding pointer and removal of buttonSpacing, which I'm unsure about is good or not).

**Comment by retrixe** [comment]
Yet, I need this pull request for reference.

**Comment by radi-cho** [comment]
Ok... -.-

**Comment by retrixe** [comment]
See d02698f. We just need to use flexbox to move images to the bottom. That's about it.

**Comment by radi-cho** [comment]
OK.

**Pull request closed without merging**
